apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-app-deployment
spec:
  selector:
    matchLabels:
      app: my-first-app-pod
  template:
    metadata:
      labels:
        app: my-first-app-pod
    spec:
      containers:
      - name: my-first-app-container
        image: huynguyencontainer.azurecr.io/myapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        
